theme = "onedark"

[editor]
line-number = "relative"
# Ignore git diff inside sidebar
gutters = ["diagnostics", "spacer", "line-numbers"]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "Â·"
nbsp = "ğŸš©"
tab = "â†’"
newline = "â"
tabpad = "Â·" # Tabs will look like "â†’Â·Â·Â·" (depending on tab width)

[editor.soft-wrap]
enable = true
